cargo-features=["edition2024"]

[package]
name = "proxy"
version = "0.1.0"
edition = "2024"

[dependencies]
smol = "1.3"
smol-potat = "1.1"
async-net = "1.7"
async-h1 = "2.3" 
surf = "2.3"
http-types = "2.12"
